
services:
  scolarite_postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: bombe
      POSTGRES_PASSWORD: bombe
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  # notes_postgres:
    networks:
      - gateway

  # authentication:
  #   image: quarkus-service-authentication-graph:latest
  #   container_name: quarkus-service-authentication-graph
  #   ports:
  #     - "8091:8091"
  #   environment:
  #     - QUARKUS_PROFILE=dev
  #     - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/authentication
  #     - QUARKUS_DATASOURCE_USERNAME=postgres
  #     - QUARKUS_DATASOURCE_PASSWORD=postgres
  #   depends_on:
  #     - scolarite_postgres

  quarkus-service-scolarite:
    build: 
      context: ./quarkus-service-scolarite/src/main/docker/
      dockerfile: Dockerfile.jvm
    restart: always
    image: quarkus/quarkus-scolarite:latest
    container_name: quarkus-service-scolarite
    ports:
      - "8099:8099"
    environment: 
      - QUARKUS_PROFILE=dev
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://scolarite_postgres:5432/postgres
      - QUARKUS_DATASOURCE_USERNAME=bombe
      - QUARKUS_DATASOURCE_PASSWORD=bombe
    depends_on:
      - scolarite_postgres

    networks:
      - gateway

  quarkus-service-classe-personnel:
    build: 
      context: ./quarkus-service-classe-personnel/src/main/docker/
      dockerfile: Dockerfile.jvm

    image: quarkus/quarkus-staff:latest
    container_name: quarkus-service-classe-personnel
    ports:
      - "8092:8092"
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://scolarite_postgres:5432/postgres
      - QUARKUS_DATASOURCE_USERNAME=bombe
      - QUARKUS_DATASOURCE_PASSWORD=bombe
    depends_on:
      - scolarite_postgres
    networks:
      - gateway
  
  # notes:
  #   image: quarkus-service-notes-graph:latest
  #   container_name: quarkus-service-notes-graph
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - QUARKUS_PROFILE=dev
  #     - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/notes
  #     - QUARKUS_DATASOURCE_USERNAME=postgres
  #     - QUARKUS_DATASOURCE_PASSWORD=postgres
  #   depends_on:
  #     - notes_mongodb

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/config.conf
    links:
      - quarkus-service-scolarite
      - quarkus-service-classe-personnel

    networks:
      - gateway


networks:
  gateway:
    driver: bridge
      

#
#
#
#  char* my_join( string_array *param1, char *param2 ){
#  https://www.youtube.com/watch?v=Pfq5M2B3pvs&t=114s
#   https://www.youtube.com/playlist?list=PLJuTqSmOxhNtS9Z37Uut14fPwpdtz6Fdh
#