spring:
  application:
    name: authentication_service

server:
  servlet:
    context-path: /auth

  port: 8090


app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: 1c2d3e4f5g6h7i8j9k0l
       
    auth-server-url: http://localhost:8090/realms/quarkus
    realm: quarkus
    resource: authentication_service