package org.acme.aws.reactive_quarkus.simple.global;

public enum DocumentType {
    CERTIFICATE_OF_SCHOOL_ATTENDANCE,
    SCHOOL_REPORT,
    SCHOOL_CERTIFICATE,
    SCHOOL_TRANSCRIPT,
    SCHOOL_DIPLOME_UNIVERSITY,
    SCHOOL_DIPLOME_SECONDARY,
    CNI,
    SCHOOL_CERTIFICATE_OF_ACHIEVEMENT,
    SCHOOL_CERTIFICATE_OF_EXCELLENCE,
    SCHOOL_CERTIFICATE_OF_PARTICIPATION,
    SCHOOL_CERTIFICATE_OF_RECOGNITION
}
