
name: MICROSERVICES_SUPERIEURS_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Test
        run: mvn test
      - name: Deploy  

        run: echo "Add your deploy steps here"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV_VAR_1: ${{ secrets.ENV_VAR_1 }}
          ENV_VAR_2: ${{ secrets.ENV_VAR_2 }}
          ENV_VAR_3: ${{ secrets.ENV_VAR_3 }}
          ENV_VAR_4: ${{ secrets.ENV_VAR_4 }}
          ENV_VAR_5: ${{ secrets.ENV_VAR_5 }}
          ENV_VAR_6: ${{ secrets.ENV_VAR_6 }}
          ENV_VAR_7: ${{ secrets.ENV_VAR_7 }}
          ENV_VAR_8: ${{ secrets.ENV_VAR_8 }}
          ENV_VAR_9: ${{ secrets.ENV_VAR_9 }}